### ISSUE TITLE
Should we make this a preset?

### ISSUE THREAD

**Issue by danmakenoise** [micnews/miclint#53]
Hey all!

I've been thinking we should ditch the CLI, and move this to something more like `eslint-preset-mic` for several reasons:

* Having eslint configs in each of our repos will allow for easy rule overriding for very repo-specific needs.
* Using eslint in our open-source libraries will make it easier for folks to contribute to our code.
* Using eslint directly will make editor integration easier for all.

Anyone disagree or agree?

**Comment by ellell** [comment]
Yeah don't see a reason not to make the eslint config here available directly. We should be able to easily use both side by side though right? I mean there's no need to deprecate the cli part here. We can just make the config exportable/sharable.

**Comment by danmakenoise** [comment]
@ellell yep! My thoughts exactly.

**Comment by ellell** [comment]
Fixed by https://github.com/micnews/miclint/pull/54
